version: '3'
services:
  app:
    build: .
    container_name: go-resume
    ports:
      - "${HOST_PORT}:8080"
    restart: unless-stopped
    volumes:
      - ./resume.yaml:/go/src/app/resume.yaml # ENABLES LIVE-EDITING
      #- ./resume.html:/go/src/app/resume.html # ONLY FOR DEBUGGING
